### ISSUE TITLE
Keyboard covers EditText when shown

### ISSUE THREAD

**Issue by borgwald** [instachat/emoji-library#4]
Hello,

when showing the Keyboard it covers the EditText. The smiley to open the emoji-fragment for example can hardly be seen. I am using the WhatsAppPanel in my xml-file.

![screenshot_2016-08-07-20-09-05](https://cloud.githubusercontent.com/assets/2222317/17464265/2126fcd2-5cdb-11e6-9df9-b1a2c3d4e604.png)

**Comment by borgwald** [comment]
noticed that the height in R.layout.rsc_emojikeyboard is hardcoded with 263dip. And the standard Keyboard is larger than 263dp when word-suggestions are enabled.

**Comment by edsilfer** [comment]
Hi, unfortunately I lack time to work on this issue right now. I've checked in my current project and whats app panel is working as expected even with word-suggestions. What I adivice you, is to create your own panel class, just copy and paste the content from whats app or telegram one. Once done that, change the fix height of the keyboard in order to adjust to your screen. This is kind of weird though, 'cause this height should be the same for all devices. 

![screenshot_20160808-102144](https://cloud.githubusercontent.com/assets/12755321/17483215/8b5ac068-5d5b-11e6-9ec9-1ad2a8be4867.png)

**Comment by edsilfer** [comment]
Best approach would be to clone the project and alter the size of the keyboard.

**Comment by erikswed** [comment]
Actually for me, adding this to AndroidManifest `android:windowSoftInputMode="adjustPan"` fixes this problem
