### ISSUE TITLE
Duplicate android:name in manifest's application

### ISSUE THREAD

**Issue by jackie-d** [instachat/emoji-library#6]
Hello,
 I have added your library to my project in Android Studio and got this error.

`Error:Execution failed for task ':app:processDebugManifest'.
 \> Manifest merger failed : Attribute application@name value=(com.giacomodeglinnocenti.myappname.MyAppName) from AndroidManifest.xml:15:9-36
    is also present at [br.com.instachat:emoji-library:0.0.2] AndroidManifest.xml:12:9-62 value=(br.com.instachat.emojilibrary.util.App).
    Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:14:5-92:19 to override.`

In my build.gradle I have added the following line:

`compile 'br.com.instachat:emoji-library:0.0.2'`

The error goes away if I modify my `AndroidManifest.xml`'s application node adding `tools:replace="android:name"`, but if course I want my application name to be MyAppName and not Instachat.

What do I have to do?
Thanks.

**Comment by edsilfer** [comment]
Your application name is define on `android:label` attribute not `android:name`. `android:name` attribute reffers to the class that will extend the Application class and, usually, called in order to obtain a context to get resources from common classes. I don't see a problem using replace in this case. Can you be more specific? If the name of the app is being changed to Instachat, try adding label to the `tools:replace` attribute as indicated in [this ](http://stackoverflow.com/questions/25981156/tools-replace-not-replacing-in-android-manifest) thread
