### ISSUE TITLE
Cannot resolve symbol 'prepareKeyboard'

### ISSUE THREAD

**Issue by jackie-d** [instachat/emoji-library#7]
I'm trying to use this amazing library, that seems to have everything I need for the emoji implementation and I really want to use this!

I added `compile 'br.com.instachat:emoji-library:0.0.2'` to my build.gradle.

I have modified my ChatActivity as follow:

```
public class ChatActivity extends EmojiCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_chat);
        EmojiEditText input = (EmojiEditText) findViewById(R.id.message_edittext);
        prepareKeyboard(this, input);
    }
}
```

and my layout is the following:

```
<LinearLayout android:layout_width="match_parent"
     android:layout_height="wrap_content"
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:orientation="horizontal">

         <br.com.instachat.emojilibrary.model.layout.EmojiEditText
             android:id="@+id/message_edittext"
             android:layout_width="200dp"
             android:layout_height="50dp"
             android:hint="Message"
             app:emojiSize="25dip"/>

 </LinearLayout>
```

And I got this compilation error (and also Android Studio show the error )

`Error:(10, 9) error: cannot find symbol method prepareKeyboard(ChatActivity,EmojiEditText)`

I know that the library has been correctly imported because I am capable of using `EmojiEditText` class in Android Studio, and also I can look into `EmojiCompatActivity` by the IDE. As I can see there is no `prepareKeyboard` method inside `EmojiCompatActivity` and I have not found it in any 
android docs, so I'm questioning myself where is this method descending from?

Thank you, Cheers

**Comment by edsilfer** [comment]
I`m sorry, documentation is misleading. Well, in order to implement the raw emoji library, it might take you a while since it is not straight forward to deal with all soft keyboard events. Have you looked at the [wiki](https://github.com/instachat/emoji-library/wiki/Development) section? I recommend you to try either, WhatsApp or Telegram Panel in order to get a fast result for your project. Otherwise, I adive you to open the implementation classes of the mentioned panels and repeate the same implementation,

You're right, the prepareKeyboard no longer seems to exist.

Also, latest version is 1.0.8, I forgot to update the README as well.

**Comment by jackie-d** [comment]
Ok, thank you.
